version: '3.8'

services:

  mcp-server:
    container_name: mcp-server
    ports:
      - "8081:8081"  # Expose MCP server to host
    environment:
      - CRUD_API_URL=http://crud-app:8080
    networks:
      - springnet
    depends_on:
      - app

networks:
  app-network:
    driver: springnet