spring.application.name=MCPServer
mcp.crud-base-url=http://localhost:8080
spring.ai.mcp.server.type=SYNC
spring.ai.mcp.server.name=mcp-server
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.transport=stdio
spring.ai.mcp.server.enabled=true
spring.main.web-application-type=none
spring.main.banner-mode=off
logging.pattern.console=
logging.level.root=ERROR
logging.stdout.threshold=OFF
#spring.main.banner-mode=off
#logging.level.root=OFF
#logging.pattern.console=

logging.file.name=./model-context-protocol/weather/starter-stdio-server/target/mcp-weather-stdio-server.log